title: Developer Blog
author: Developer
description: Passionate programmer ğŸ”¥ Web Developer  ğŸ› ï¸


# social links
theme: minima
show_excerpts: false # set to false to remove excerpts on the homepage